doma:
  dialect: mysql
  sql-file-repository: no_cache

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/motion?useSSL=false
    username: root
    password: root