doma:
  dialect: mysql
  sql-file-repository: no_cache

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/motion
    username: root
    password: root