openapi: 3.0.1
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://apiss.example.com'
paths:
  /motion/{deviceId}:
    get:
      summary: 全モーションデータを取得
      description: 運動量に関わる全てのモーションデータを返却します
      tags:
        - front
      parameters:
        - name: deviceId
          in: path
          description: デバイスID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: モーションデータ一覧
          content:
            application/json:
              schema:
                description: モーションデータの全量を返却する。返却パラメータは全てdouble型
                type: array
                items:
                  $ref: '#/components/schemas/Moment'
                example:
                  registerTimestamp: 2019-03-29 16:00:51
                  accelerationmeter_x: 10.5
                  accelerationmeter_y: 10.5
                  accelerationmeter_z: 10.5
                  gyroscope_x: -10.5
                  gyroscope_y: -7.5
                  gyroscope_z: 2.5
                  magnetometer_x: -0.6
                  magnetometer_y: 0.0
                  magnetometer_z: 1.0
                  luxometer: 123.4
        '404':
          description: デバイスIDに紐づくデータが存在しない
        '500':
          description: サーバーエラー
    post:
      summary: モーションデータを登録
      description: 運動量に関わる全てのモーションデータをDBに登録します
      tags:
        - router
      parameters:
        - name: deviceId
          in: path
          description: デバイスID
          required: true
          schema:
            type: string
      requestBody:
        description: 運動量
        required: true
        content:
          application/json:
            schema:
              description: 登録するモーションデータを設定する。返却パラメータは全てdouble型
              $ref: '#/components/schemas/Moment'
      responses:
        '200':
          description: 正常終了
        '400':
          description: リクエスト構文
        '500':
          description: サーバーエラー

components:
  schemas:
    Moment:
      description: 運動量
      type: object
      properties:
        registerTimestamp:
          description: 登録タイムスタンプ
          type: string
          example:
            2019-03-29 16:00:51
        accelerationmeter_x:
          description: X軸加速度
          type: number
          format: double
          example:
            10.5
        accelerationmeter_y:
          description: Y軸加速度
          type: number
          format: double
          example:
            10.5
        accelerationmeter_z:
          description: Z軸加速度
          type: number
          format: double
        gyroscope_x:
          description: X軸角加速度
          type: number
          format: double
        gyroscope_y:
          description: Y軸角加速度
          type: number
          format: double
        gyroscope_z:
          description: Z軸角加速度
          type: number
          format: double
        magnetometer_x:
          description: X軸地磁気強度
          type: number
          format: double
        magnetometer_y:
          description: Y軸地磁気強度
          type: number
          format: double
        magnetometer_z:
          description: Z軸地磁気強度
          type: number
          format: double
        luxometer:
          description: 光度
          type: number
          format: double